const GET_REPOSITORIES_URL = "search/repositories";
const GET_STARRED_REPOSITORIES_URL = "user/starred";
const STAR_UNSTAR_REPOSITORY_URL = "user/starred";

export {
  GET_REPOSITORIES_URL,
  GET_STARRED_REPOSITORIES_URL,
  STAR_UNSTAR_REPOSITORY_URL,
};
